#!/bin/bash
# Employee Assistant — Setup Script
# Walks the user through creating their Supabase project and configuring env vars.

set -e

BOLD="\033[1m"
CYAN="\033[36m"
GREEN="\033[32m"
YELLOW="\033[33m"
RED="\033[31m"
RESET="\033[0m"

echo ""
echo -e "${CYAN}${BOLD}══════════════════════════════════════════════${RESET}"
echo -e "${CYAN}${BOLD}    Employee Assistant — Setup Wizard${RESET}"
echo -e "${CYAN}${BOLD}══════════════════════════════════════════════${RESET}"
echo ""

# ─── Step 1: Employee Info ───────────────────────────────────────────
echo -e "${BOLD}Step 1: Employee Info${RESET}"
echo ""

read -p "Employee name: " EMPLOYEE_NAME
read -p "Employee role/title: " EMPLOYEE_ROLE
read -p "Company name: " COMPANY_NAME
read -p "Employee email (for login access): " ALLOWED_EMAILS

echo ""

# ─── Step 2: Supabase ───────────────────────────────────────────────
echo -e "${BOLD}Step 2: Supabase Setup${RESET}"
echo ""
echo -e "1. Go to ${CYAN}https://supabase.com/dashboard${RESET}"
echo "2. Create a new project (name it something like 'employee-assistant-${EMPLOYEE_NAME// /-}')"
echo "3. Wait for the project to finish provisioning"
echo "4. Go to Project Settings → API"
echo ""

read -p "Supabase Project URL: " SUPABASE_URL
read -p "Supabase Anon (public) Key: " SUPABASE_ANON_KEY
read -sp "Supabase Service Role Key: " SUPABASE_SERVICE_KEY
echo ""

echo ""
echo -e "${YELLOW}Now run the database migration:${RESET}"
echo "1. Go to your Supabase project → SQL Editor"
echo "2. Paste the contents of supabase/migration.sql"
echo "3. Click 'Run'"
echo ""
read -p "Press Enter once you've run the migration... "

echo ""

# ─── Step 3: Anthropic API Key ───────────────────────────────────────
echo -e "${BOLD}Step 3: Anthropic API Key${RESET}"
echo ""
echo -e "Get one at ${CYAN}https://console.anthropic.com/${RESET}"
echo ""

read -sp "Anthropic API Key: " ANTHROPIC_API_KEY
echo ""
echo ""

# ─── Step 4: Google OAuth ────────────────────────────────────────────
echo -e "${BOLD}Step 4: Google OAuth (for login)${RESET}"
echo ""
echo "1. Go to https://console.cloud.google.com/apis/credentials"
echo "2. Create an OAuth 2.0 Client ID (type: Web application)"
echo "3. Add authorized redirect URIs:"
echo "   - http://localhost:3001/api/auth/callback/google (for local dev)"
echo "   - https://YOUR-VERCEL-URL/api/auth/callback/google (for production)"
echo ""

read -p "Google Client ID: " GOOGLE_CLIENT_ID
read -sp "Google Client Secret: " GOOGLE_CLIENT_SECRET
echo ""
echo ""

# ─── Step 5: NextAuth Secret ─────────────────────────────────────────
NEXTAUTH_SECRET=$(openssl rand -base64 32)
echo -e "${BOLD}Step 5: NextAuth Secret${RESET}"
echo -e "Auto-generated: ${GREEN}done${RESET}"
echo ""

# ─── Step 6: Google Calendar/Gmail (Optional) ────────────────────────
echo -e "${BOLD}Step 6: Google Calendar & Gmail (Optional)${RESET}"
echo ""
read -p "Set up Google Calendar/Gmail? (y/n): " SETUP_GOOGLE

GOOGLE_CREDENTIALS_JSON=""
GOOGLE_TOKEN_JSON=""

if [[ "$SETUP_GOOGLE" =~ ^[Yy] ]]; then
  echo ""
  echo "You need two JSON files from the Google OAuth flow:"
  echo "  1. credentials.json — downloaded from Google Cloud Console"
  echo "  2. token.json — generated by running the OAuth flow"
  echo ""
  echo "If you have these files, enter their paths below."
  echo "If not, skip this and set them up later."
  echo ""

  read -p "Path to credentials.json (or press Enter to skip): " CRED_PATH
  read -p "Path to token.json (or press Enter to skip): " TOKEN_PATH

  if [[ -n "$CRED_PATH" && -f "$CRED_PATH" ]]; then
    GOOGLE_CREDENTIALS_JSON=$(cat "$CRED_PATH" | tr -d '\n')
  fi
  if [[ -n "$TOKEN_PATH" && -f "$TOKEN_PATH" ]]; then
    GOOGLE_TOKEN_JSON=$(cat "$TOKEN_PATH" | tr -d '\n')
  fi
fi

echo ""

# ─── Write .env.local ────────────────────────────────────────────────
echo -e "${BOLD}Writing .env.local...${RESET}"

cat > .env.local << ENVEOF
# Employee Assistant — Generated by setup.sh
# $(date)

# NextAuth
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
NEXTAUTH_URL=http://localhost:3001

# Google OAuth
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

# Access control
ALLOWED_EMAILS=${ALLOWED_EMAILS}

# Anthropic
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

# Supabase
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_KEY}

# Employee context
EMPLOYEE_NAME=${EMPLOYEE_NAME}
EMPLOYEE_ROLE=${EMPLOYEE_ROLE}
COMPANY_NAME=${COMPANY_NAME}

# Google Calendar/Gmail (optional)
GOOGLE_CREDENTIALS_JSON=${GOOGLE_CREDENTIALS_JSON}
GOOGLE_TOKEN_JSON=${GOOGLE_TOKEN_JSON}
ENVEOF

echo -e "${GREEN}✓ .env.local written${RESET}"
echo ""

# ─── Install & Test ──────────────────────────────────────────────────
echo -e "${BOLD}Installing dependencies...${RESET}"
npm install --silent 2>/dev/null

echo ""
echo -e "${GREEN}${BOLD}══════════════════════════════════════════════${RESET}"
echo -e "${GREEN}${BOLD}    Setup Complete!${RESET}"
echo -e "${GREEN}${BOLD}══════════════════════════════════════════════${RESET}"
echo ""
echo -e "  ${BOLD}To run locally:${RESET}"
echo "    npm run dev"
echo "    Open http://localhost:3001"
echo ""
echo -e "  ${BOLD}To deploy to Vercel:${RESET}"
echo "    1. Push this repo to GitHub"
echo "    2. Import it in Vercel (https://vercel.com/new)"
echo "    3. Add the env vars from .env.local to Vercel's Environment Variables"
echo "       (change NEXTAUTH_URL to your Vercel URL)"
echo "    4. Add your Vercel URL to Google OAuth redirect URIs:"
echo "       https://YOUR-APP.vercel.app/api/auth/callback/google"
echo ""
echo -e "  ${BOLD}Employee:${RESET} ${EMPLOYEE_NAME} (${EMPLOYEE_ROLE})"
echo -e "  ${BOLD}Company:${RESET} ${COMPANY_NAME}"
echo -e "  ${BOLD}Login:${RESET} ${ALLOWED_EMAILS}"
echo ""
